### ISSUE TITLE
Coordinate system seems to be wrong

### ISSUE THREAD

**Issue by magdesign** [bferrarese/raster2laser_gcode#1]
I compared the output from the original script on Inkscape 0.92 and your script. The first line of code (after the header) in your script, always writes:
`G0 X0.0 Y0.0`

and also all the other coordinates differ a lot.

left side=yours    ...............................................         right side=original

![diff3](https://user-images.githubusercontent.com/5273166/82217246-70ddb980-991a-11ea-9183-910ba8802427.png)

Attached a .zip with the .svg file, the output from 305enineering original and from your mod:
[cnc_test.zip](https://github.com/bferrarese/raster2laser_gcode/files/4644251/cnc_test.zip)

(used a document with 600x400mm. Ignore that I changed G00 to G0, since its a modification my machine needs...)

As seen in the release notes (https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#origin), they changed the coordinate system.. think there is the problem.

Changed in Inkscape settings under Preferences =>Interface =>  "Origin at upper left " which did not help.

**Comment by bferrarese** [comment]
I don't like the G00/G01 too. Changed to G0/G1

**Comment by bferrarese** [comment]
btw, you need all those M3/M5? My machine understands G0 as laser off and G1 as laser automatically.

**Comment by magdesign** [comment]
M3/M5 => Not sure about this, my laser also understands only on/off, have an Arduino with Lasersaur on it to control the machine. After reading the specs (https://github.com/nortd/lasersaur/wiki/gcode) I think G0/G1 works.

There is also the issue that with acceleration, the motors slow down when they come to the edge and then there it gives deeper engravings. A workaround would be to overshoot every edge by ~4mm but turn off the laser in the right time ;-)

**Comment by bferrarese** [comment]
Cool...looks like you don't need M3/M5.

Yeah...I have the same issue with darker edges. We definitely need to work on that.

Now, from the screen that pops up when you call the extension... what can we do better? Which controls you use the most? Which ones are not used?

**Comment by magdesign** [comment]
:-) I always use the same setting: 10px/mm, BW fixed (convert the images beforehand to BW), Flip Y, and the speed setting somehow does not really matter. But I guess this is a problem on the Lasersaur side.
Also why do we have to rename the *.txt file to *.ngc, why not just outputting a *.ngc?

Engraving is always very slow. If we could engrave with a speed of 2000 and with full laser power we could save hours, of course for this the overshoot setting would be important to get a constant burn.

**Comment by bferrarese** [comment]
Check it out ...

blue = laser on
gray = laser off (move - G0)
 
![Screenshot from 2020-05-18 16-13-51](https://user-images.githubusercontent.com/47937307/82260598-34628b80-9923-11ea-85cf-e160dfdfb34d.png)

Please try commit and let me know.

(far from final... you will see different files / file names.... just my debugs)... btw, you only care for the .ngc right? if that's the case I'll move other to /tmp

**Comment by magdesign** [comment]
Wow.
Looks good so far, the software reads the file correct and the Lasersaur displays the logo!
Will try it in real and report, but currently we have middle in the night and I am not able to fire up the laser.... ;-)

**Comment by bferrarese** [comment]
cool..no worries.

I have two new commits... implemented correct (I hope) feed and power control. Try previous commits if you have issues.

**Comment by magdesign** [comment]
congratulation!
It works as expected in Inkscape 1.0
Thank you, thank you, thank you.

![image20200520_105834827](https://user-images.githubusercontent.com/5273166/82427942-0fd4f380-9a8a-11ea-94af-01b5a3cd8bb7.jpg)


Can I offer you a drink via paypal?

**Comment by bferrarese** [comment]
I'm happy it is working for you.

A drink? Yeah, why not? Give me a couple of minutes to enable that. Thank you

**Comment by bferrarese** [comment]
https://www.paypal.me/bferrarese
