### ISSUE TITLE
Windows version file name issue

### ISSUE THREAD

**Issue by Zaaphod** [bferrarese/raster2laser_gcode#2]
I'm trying to get this to work on Windows 10 with Inkscape 1.0 
I keep getting the following errors:
Traceback (most recent call last):
  File "raster2laser_gcode.py", line 508, in <module>
    _main()
  File "raster2laser_gcode.py", line 504, in _main
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "raster2laser_gcode.py", line 141, in effect
    self.PNGtoGcode(pos_file_png_original, pos_file_png_BW, pos_file_png_GS, pos_file_gcode)
  File "raster2laser_gcode.py", line 179, in PNGtoGcode
    reader = png.Reader(pos_file_png_original)#File PNG generato
  File "C:\Program Files\Inkscape\share\inkscape\extensions\png.py", line 1376, in __init__
    self.file = open(kw["filename"], "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'x:\\\Laser\\\test_BWfix_128_-orignal.png'

for some reason the windows version is making my path with double \s it should be "x:\Laser\test_BWfix_128_-orignal.png"  not with the double  \\\s
There doesn't seem to be any way of tricking this to work, I've tried exporting to just my X: drive with no path, and I tried putting the \ in front of the file name.. I either get no \ or two \\\s but never the required single \

Here is a screenshot
![error](https://user-images.githubusercontent.com/3008560/85231766-e9c3ab80-b3c7-11ea-859f-216a44bdbd3c.png)

**Comment by bferrarese** [comment]
Hi Zaaphod. I guess I did not see an email about your issue...sorry. You still need me to take a look at it?

**Comment by Zaaphod** [comment]
That would be great, I have never been able to get past this error

**Comment by bferrarese** [comment]
Try again please. (No windows here for me to test)

**Comment by Zaaphod** [comment]
Thank you for working on this, I'm happy to help you test it on windows.

I'm getting the same error and it's still showing double backslashes
Here is what I get now:

![error2](https://user-images.githubusercontent.com/3008560/88961714-65403480-d273-11ea-8132-d51466e912dd.png)

**Comment by bferrarese** [comment]
I'm looking at the code and I need to rewrite parts of the original code. Unfortunately this is something that I can't do right now. I'll let you know when I have it ready.

**Comment by SidneyBovet** [comment]
I could possibly have a look at that ;)

Am I right in thinking that the command run at [raster2laser_gcode.py#L165](https://github.com/bferrarese/raster2laser_gcode/blob/230651e746664064ad888eb3bf2c06dc0c59add5/raster2laser_gcode.py#L165)  (`inkscape -C -o ...`) won't work on Windows because the shell doesn't know what the `inkscape` command is?

**Comment by bferrarese** [comment]
That would be awesome brother. 
The answer is yes and no. 
Definitely it's path related. It's the way windows paths are handled. (the backslash, which is used to scape chars)
The original code uses the old os.path/os.path.join()
Ideally we need to convert all path handling to a more modern approach like pathlib.
Please feel free to mess around. :)

**Comment by SidneyBovet** [comment]
Turns out it was because the command executed ends with `2>/dev/null`, which Windows doesn't know how to handle. Using `stderr=subprocess.PIPE` in the Popen constructor of the process achieves the same result, but works on either platform.

The pull request addresses some other points too, so let's discuss all of this in there!

**Comment by bferrarese** [comment]
Closing this one. Thanks @SidneyBovet !
