### ISSUE TITLE
Feature Request: Add Field for custom extension of Gcode

### ISSUE THREAD

**Issue by Zaaphod** [bferrarese/raster2laser_gcode#5]
It would be handy if I didn't have to rename the final output every time from .ngc to .tap  Since everyone's machines use different extensions for Gcode files, this would be convenient.

**Comment by bferrarese** [comment]
@Zaaphod 
I also removed a lost/unused variable.. curious if all is working on your windows side of the force. :)
Please git it a try and let me know.

**Comment by Zaaphod** [comment]
I just tried it and it seems to be working perfectly.  Thank you for adding an option for the extension.

**Comment by bferrarese** [comment]
Sweet....closing
